// <auto-generated/>

#nullable disable

using NUnit.Framework;
using OpenAI;
using OpenAI.Responses;
using System.ClientModel.Primitives;

namespace Azure.AI.Extensions.OpenAI
{
    /// <summary>
    /// Context class which will be filled in by the System.ClientModel.SourceGeneration.
    /// For more information <see href='https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/System.ClientModel/src/docs/ModelReaderWriterContext.md' />
    /// </summary>
    [ModelReaderWriterBuildable(typeof(BingGroundingSearchConfiguration))]
    [ModelReaderWriterBuildable(typeof(BingGroundingOptions))]
    [ModelReaderWriterBuildable(typeof(BingGroundingTool))]
    [ModelReaderWriterBuildable(typeof(BingGroundingAzureTool))]
    [ModelReaderWriterBuildable(typeof(UnknownAzureResponsesTool))]
    [ModelReaderWriterBuildable(typeof(AzureResponsesTool))]
    public partial class AzureAIExtensionsOpenAIContext : ModelReaderWriterContext
    {
    }
}
