// <auto-generated/>

#nullable disable

using System;
using System.ComponentModel;

namespace Azure.AI.Extensions.OpenAI
{
    /// <summary></summary>
    internal readonly partial struct AzureResponsesToolKind : IEquatable<AzureResponsesToolKind>
    {
        private readonly string _value;
        private const string FunctionValue = "function";
        private const string FileSearchValue = "file_search";
        private const string ComputerValue = "computer";
        private const string ComputerUsePreviewValue = "computer_use_preview";
        private const string WebSearchValue = "web_search";
        private const string McpValue = "mcp";
        private const string CodeInterpreterValue = "code_interpreter";
        private const string ImageGenerationValue = "image_generation";
        private const string LocalShellValue = "local_shell";
        private const string ShellValue = "shell";
        private const string CustomValue = "custom";
        private const string NamespaceValue = "namespace";
        private const string ToolSearchValue = "tool_search";
        private const string WebSearchPreviewValue = "web_search_preview";
        private const string ApplyPatchValue = "apply_patch";
        private const string A2aPreviewValue = "a2a_preview";
        private const string BingCustomSearchPreviewValue = "bing_custom_search_preview";
        private const string BrowserAutomationPreviewValue = "browser_automation_preview";
        private const string FabricDataagentPreviewValue = "fabric_dataagent_preview";
        private const string SharepointGroundingPreviewValue = "sharepoint_grounding_preview";
        private const string MemorySearchPreviewValue = "memory_search_preview";
        private const string WorkIqPreviewValue = "work_iq_preview";
        private const string AzureAiSearchValue = "azure_ai_search";
        private const string AzureFunctionValue = "azure_function";
        private const string BingGroundingValue = "bing_grounding";
        private const string CaptureStructuredOutputsValue = "capture_structured_outputs";
        private const string OpenapiValue = "openapi";

        /// <summary> Initializes a new instance of <see cref="AzureResponsesToolKind"/>. </summary>
        /// <param name="value"> The value. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="value"/> is null. </exception>
        public AzureResponsesToolKind(string value)
        {
            Argument.AssertNotNull(value, nameof(value));

            _value = value;
        }

        /// <summary> Gets the Function. </summary>
        public static AzureResponsesToolKind Function { get; } = new AzureResponsesToolKind(FunctionValue);

        /// <summary> Gets the FileSearch. </summary>
        public static AzureResponsesToolKind FileSearch { get; } = new AzureResponsesToolKind(FileSearchValue);

        /// <summary> Gets the Computer. </summary>
        public static AzureResponsesToolKind Computer { get; } = new AzureResponsesToolKind(ComputerValue);

        /// <summary> Gets the ComputerUsePreview. </summary>
        public static AzureResponsesToolKind ComputerUsePreview { get; } = new AzureResponsesToolKind(ComputerUsePreviewValue);

        /// <summary> Gets the WebSearch. </summary>
        public static AzureResponsesToolKind WebSearch { get; } = new AzureResponsesToolKind(WebSearchValue);

        /// <summary> Gets the Mcp. </summary>
        public static AzureResponsesToolKind Mcp { get; } = new AzureResponsesToolKind(McpValue);

        /// <summary> Gets the CodeInterpreter. </summary>
        public static AzureResponsesToolKind CodeInterpreter { get; } = new AzureResponsesToolKind(CodeInterpreterValue);

        /// <summary> Gets the ImageGeneration. </summary>
        public static AzureResponsesToolKind ImageGeneration { get; } = new AzureResponsesToolKind(ImageGenerationValue);

        /// <summary> Gets the LocalShell. </summary>
        public static AzureResponsesToolKind LocalShell { get; } = new AzureResponsesToolKind(LocalShellValue);

        /// <summary> Gets the Shell. </summary>
        public static AzureResponsesToolKind Shell { get; } = new AzureResponsesToolKind(ShellValue);

        /// <summary> Gets the Custom. </summary>
        public static AzureResponsesToolKind Custom { get; } = new AzureResponsesToolKind(CustomValue);

        /// <summary> Gets the Namespace. </summary>
        public static AzureResponsesToolKind Namespace { get; } = new AzureResponsesToolKind(NamespaceValue);

        /// <summary> Gets the ToolSearch. </summary>
        public static AzureResponsesToolKind ToolSearch { get; } = new AzureResponsesToolKind(ToolSearchValue);

        /// <summary> Gets the WebSearchPreview. </summary>
        public static AzureResponsesToolKind WebSearchPreview { get; } = new AzureResponsesToolKind(WebSearchPreviewValue);

        /// <summary> Gets the ApplyPatch. </summary>
        public static AzureResponsesToolKind ApplyPatch { get; } = new AzureResponsesToolKind(ApplyPatchValue);

        /// <summary> Gets the A2aPreview. </summary>
        public static AzureResponsesToolKind A2aPreview { get; } = new AzureResponsesToolKind(A2aPreviewValue);

        /// <summary> Gets the BingCustomSearchPreview. </summary>
        public static AzureResponsesToolKind BingCustomSearchPreview { get; } = new AzureResponsesToolKind(BingCustomSearchPreviewValue);

        /// <summary> Gets the BrowserAutomationPreview. </summary>
        public static AzureResponsesToolKind BrowserAutomationPreview { get; } = new AzureResponsesToolKind(BrowserAutomationPreviewValue);

        /// <summary> Gets the FabricDataagentPreview. </summary>
        public static AzureResponsesToolKind FabricDataagentPreview { get; } = new AzureResponsesToolKind(FabricDataagentPreviewValue);

        /// <summary> Gets the SharepointGroundingPreview. </summary>
        public static AzureResponsesToolKind SharepointGroundingPreview { get; } = new AzureResponsesToolKind(SharepointGroundingPreviewValue);

        /// <summary> Gets the MemorySearchPreview. </summary>
        public static AzureResponsesToolKind MemorySearchPreview { get; } = new AzureResponsesToolKind(MemorySearchPreviewValue);

        /// <summary> Gets the WorkIqPreview. </summary>
        public static AzureResponsesToolKind WorkIqPreview { get; } = new AzureResponsesToolKind(WorkIqPreviewValue);

        /// <summary> Gets the AzureAiSearch. </summary>
        public static AzureResponsesToolKind AzureAiSearch { get; } = new AzureResponsesToolKind(AzureAiSearchValue);

        /// <summary> Gets the AzureFunction. </summary>
        public static AzureResponsesToolKind AzureFunction { get; } = new AzureResponsesToolKind(AzureFunctionValue);

        /// <summary> Gets the BingGrounding. </summary>
        public static AzureResponsesToolKind BingGrounding { get; } = new AzureResponsesToolKind(BingGroundingValue);

        /// <summary> Gets the CaptureStructuredOutputs. </summary>
        public static AzureResponsesToolKind CaptureStructuredOutputs { get; } = new AzureResponsesToolKind(CaptureStructuredOutputsValue);

        /// <summary> Gets the Openapi. </summary>
        public static AzureResponsesToolKind Openapi { get; } = new AzureResponsesToolKind(OpenapiValue);

        /// <summary> Determines if two <see cref="AzureResponsesToolKind"/> values are the same. </summary>
        /// <param name="left"> The left value to compare. </param>
        /// <param name="right"> The right value to compare. </param>
        public static bool operator ==(AzureResponsesToolKind left, AzureResponsesToolKind right) => left.Equals(right);

        /// <summary> Determines if two <see cref="AzureResponsesToolKind"/> values are not the same. </summary>
        /// <param name="left"> The left value to compare. </param>
        /// <param name="right"> The right value to compare. </param>
        public static bool operator !=(AzureResponsesToolKind left, AzureResponsesToolKind right) => !left.Equals(right);

        /// <summary> Converts a string to a <see cref="AzureResponsesToolKind"/>. </summary>
        /// <param name="value"> The value. </param>
        public static implicit operator AzureResponsesToolKind(string value) => new AzureResponsesToolKind(value);

        /// <summary> Converts a string to a <see cref="AzureResponsesToolKind"/>. </summary>
        /// <param name="value"> The value. </param>
        public static implicit operator AzureResponsesToolKind?(string value) => value == null ? null : new AzureResponsesToolKind(value);

        /// <inheritdoc/>
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object obj) => obj is AzureResponsesToolKind other && Equals(other);

        /// <inheritdoc/>
        public bool Equals(AzureResponsesToolKind other) => string.Equals(_value, other._value, StringComparison.InvariantCultureIgnoreCase);

        /// <inheritdoc/>
        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value != null ? StringComparer.InvariantCultureIgnoreCase.GetHashCode(_value) : 0;

        /// <inheritdoc/>
        public override string ToString() => _value;
    }
}