// <auto-generated/>

#nullable disable

using OpenAI;
using OpenAI.Responses;
using System;
using System.ClientModel.Primitives;
using System.Collections.Generic;
using System.Text.Json;

namespace Azure.AI.Extensions.OpenAI
{
    /// <summary>
    /// A tool that can be used to generate a response.
    /// Please note this is the abstract base class. The derived classes available for instantiation are: <see cref="BingGroundingAzureTool"/>, <see cref="ResponsesMicrosoftFabricPreviewTool"/>, <see cref="ResponsesSharepointPreviewTool"/>, <see cref="ResponsesAzureAISearchTool"/>, <see cref="ResponsesOpenApiTool"/>, <see cref="ResponsesBingCustomSearchPreviewTool"/>, <see cref="ResponsesBrowserAutomationPreviewTool"/>, <see cref="ResponsesAzureFunctionTool"/>, <see cref="ResponsesCaptureStructuredOutputsTool"/>, <see cref="ResponsesA2APreviewTool"/>, <see cref="ResponsesWorkIQPreviewTool"/>, <see cref="ResponsesMemorySearchPreviewTool"/>, <see cref="ResponsesWebSearchTool"/>, <see cref="ResponsesLocalShellToolParam"/>, <see cref="ResponsesFunctionShellToolParam"/>, <see cref="ResponsesCustomToolParam"/>, <see cref="ResponsesComputerTool"/>, <see cref="ResponsesNamespaceToolParam"/>, and <see cref="ResponsesToolSearchToolParam"/>.
    /// </summary>
    [PersistableModelProxy(typeof(UnknownAzureResponsesTool))]
    public abstract partial class AzureResponsesTool : IJsonModel<AzureResponsesTool>
    {
        public static implicit operator ResponseTool(AzureResponsesTool azureResponsesTool)
        {
            // TODO: Instead of MRW.Write, this should use Patch.GetJson.
            return ModelReaderWriter.Read<ResponseTool>(
                ModelReaderWriter.Write(
                    azureResponsesTool,
                    ModelSerializationExtensions.WireOptions,
                    AzureAIExtensionsOpenAIContext.Default),
                ModelSerializationExtensions.WireOptions,
                OpenAIContext.Default);
        }

        // *****************************************************************

        /// <summary> Keeps track of any properties unknown to the library. </summary>
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        /// <summary> Initializes a new instance of <see cref="ResponsesTool"/>. </summary>
        /// <param name="type"></param>
        private protected AzureResponsesTool(AzureResponsesToolKind @type)
        {
            Type = @type;
        }

        /// <summary> Initializes a new instance of <see cref="ResponsesTool"/>. </summary>
        /// <param name="type"></param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal AzureResponsesTool(AzureResponsesToolKind @type, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            Type = @type;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        /// <summary> Gets or sets the Type. </summary>
        internal AzureResponsesToolKind Type { get; set; }

        // *****************************************************************

        /// <summary> Initializes a new instance of <see cref="AzureResponsesTool"/> for deserialization. </summary>
        internal AzureResponsesTool()
        {
        }

        /// <param name="data"> The data to parse. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        protected virtual AzureResponsesTool PersistableModelCreateCore(BinaryData data, ModelReaderWriterOptions options)
        {
            string format = options.Format == "W" ? ((IPersistableModel<AzureResponsesTool>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "J":
                    using (JsonDocument document = JsonDocument.Parse(data, ModelSerializationExtensions.JsonDocumentOptions))
                    {
                        return DeserializeResponsesTool(document.RootElement, options);
                    }
                default:
                    throw new FormatException($"The model {nameof(AzureResponsesTool)} does not support reading '{options.Format}' format.");
            }
        }

        /// <param name="options"> The client options for reading and writing models. </param>
        protected virtual BinaryData PersistableModelWriteCore(ModelReaderWriterOptions options)
        {
            string format = options.Format == "W" ? ((IPersistableModel<AzureResponsesTool>)this).GetFormatFromOptions(options) : options.Format;
            switch (format)
            {
                case "J":
                    return ModelReaderWriter.Write(this, options, AzureAIExtensionsOpenAIContext.Default);
                default:
                    throw new FormatException($"The model {nameof(AzureResponsesTool)} does not support writing '{options.Format}' format.");
            }
        }

        /// <param name="options"> The client options for reading and writing models. </param>
        BinaryData IPersistableModel<AzureResponsesTool>.Write(ModelReaderWriterOptions options) => PersistableModelWriteCore(options);

        /// <param name="data"> The data to parse. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        AzureResponsesTool IPersistableModel<AzureResponsesTool>.Create(BinaryData data, ModelReaderWriterOptions options) => PersistableModelCreateCore(data, options);

        /// <param name="options"> The client options for reading and writing models. </param>
        string IPersistableModel<AzureResponsesTool>.GetFormatFromOptions(ModelReaderWriterOptions options) => "J";

        /// <param name="writer"> The JSON writer. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        void IJsonModel<AzureResponsesTool>.Write(Utf8JsonWriter writer, ModelReaderWriterOptions options)
        {
            writer.WriteStartObject();
            JsonModelWriteCore(writer, options);
            writer.WriteEndObject();
        }

        /// <param name="writer"> The JSON writer. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        protected virtual void JsonModelWriteCore(Utf8JsonWriter writer, ModelReaderWriterOptions options)
        {
            string format = options.Format == "W" ? ((IPersistableModel<AzureResponsesTool>)this).GetFormatFromOptions(options) : options.Format;
            if (format != "J")
            {
                throw new FormatException($"The model {nameof(AzureResponsesTool)} does not support writing '{format}' format.");
            }
            writer.WritePropertyName("type"u8);
            writer.WriteStringValue(Type.ToString());
            if (options.Format != "W" && _additionalBinaryDataProperties != null)
            {
                foreach (var item in _additionalBinaryDataProperties)
                {
                    writer.WritePropertyName(item.Key);
#if NET6_0_OR_GREATER
                    writer.WriteRawValue(item.Value);
#else
                    using (JsonDocument document = JsonDocument.Parse(item.Value))
                    {
                        JsonSerializer.Serialize(writer, document.RootElement);
                    }
#endif
                }
            }
        }

        /// <param name="reader"> The JSON reader. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        AzureResponsesTool IJsonModel<AzureResponsesTool>.Create(ref Utf8JsonReader reader, ModelReaderWriterOptions options) => JsonModelCreateCore(ref reader, options);

        /// <param name="reader"> The JSON reader. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        protected virtual AzureResponsesTool JsonModelCreateCore(ref Utf8JsonReader reader, ModelReaderWriterOptions options)
        {
            string format = options.Format == "W" ? ((IPersistableModel<AzureResponsesTool>)this).GetFormatFromOptions(options) : options.Format;
            if (format != "J")
            {
                throw new FormatException($"The model {nameof(AzureResponsesTool)} does not support reading '{format}' format.");
            }
            using JsonDocument document = JsonDocument.ParseValue(ref reader);
            return DeserializeResponsesTool(document.RootElement, options);
        }

        /// <param name="element"> The JSON element to deserialize. </param>
        /// <param name="options"> The client options for reading and writing models. </param>
        internal static AzureResponsesTool DeserializeResponsesTool(JsonElement element, ModelReaderWriterOptions options)
        {
            if (element.ValueKind == JsonValueKind.Null)
            {
                return null;
            }
            if (element.TryGetProperty("type"u8, out JsonElement discriminator))
            {
                switch (discriminator.GetString())
                {
                    case "bing_grounding":
                        return BingGroundingAzureTool.DeserializeBingGroundingAzureTool(element, options);
                    //case "fabric_dataagent_preview":
                    //    return ResponsesMicrosoftFabricPreviewTool.DeserializeResponsesMicrosoftFabricPreviewTool(element, options);
                    //case "sharepoint_grounding_preview":
                    //    return ResponsesSharepointPreviewTool.DeserializeResponsesSharepointPreviewTool(element, options);
                    //case "azure_ai_search":
                    //    return ResponsesAzureAISearchTool.DeserializeResponsesAzureAISearchTool(element, options);
                    //case "openapi":
                    //    return ResponsesOpenApiTool.DeserializeResponsesOpenApiTool(element, options);
                    //case "bing_custom_search_preview":
                    //    return ResponsesBingCustomSearchPreviewTool.DeserializeResponsesBingCustomSearchPreviewTool(element, options);
                    //case "browser_automation_preview":
                    //    return ResponsesBrowserAutomationPreviewTool.DeserializeResponsesBrowserAutomationPreviewTool(element, options);
                    //case "azure_function":
                    //    return ResponsesAzureFunctionTool.DeserializeResponsesAzureFunctionTool(element, options);
                    //case "capture_structured_outputs":
                    //    return ResponsesCaptureStructuredOutputsTool.DeserializeResponsesCaptureStructuredOutputsTool(element, options);
                    //case "a2a_preview":
                    //    return ResponsesA2APreviewTool.DeserializeResponsesA2APreviewTool(element, options);
                    //case "work_iq_preview":
                    //    return ResponsesWorkIQPreviewTool.DeserializeResponsesWorkIQPreviewTool(element, options);
                    //case "memory_search_preview":
                    //    return ResponsesMemorySearchPreviewTool.DeserializeResponsesMemorySearchPreviewTool(element, options);
                    //case "code_interpreter":
                    //    return InternalCodeInterpreterTool.DeserializeInternalCodeInterpreterTool(element, options);
                    //case "function":
                    //    return InternalFunctionTool.DeserializeInternalFunctionTool(element, options);
                    //case "file_search":
                    //    return InternalFileSearchTool.DeserializeInternalFileSearchTool(element, options);
                    //case "computer_use_preview":
                    //    return InternalComputerUsePreviewTool.DeserializeInternalComputerUsePreviewTool(element, options);
                    //case "web_search":
                    //    return ResponsesWebSearchTool.DeserializeResponsesWebSearchTool(element, options);
                    //case "mcp":
                    //    return InternalMCPTool.DeserializeInternalMCPTool(element, options);
                    //case "image_generation":
                    //    return InternalImageGenTool.DeserializeInternalImageGenTool(element, options);
                    //case "local_shell":
                    //    return ResponsesLocalShellToolParam.DeserializeResponsesLocalShellToolParam(element, options);
                    //case "shell":
                    //    return ResponsesFunctionShellToolParam.DeserializeResponsesFunctionShellToolParam(element, options);
                    //case "custom":
                    //    return ResponsesCustomToolParam.DeserializeResponsesCustomToolParam(element, options);
                    //case "web_search_preview":
                    //    return InternalWebSearchPreviewTool.DeserializeInternalWebSearchPreviewTool(element, options);
                    //case "apply_patch":
                    //    return InternalApplyPatchToolParam.DeserializeInternalApplyPatchToolParam(element, options);
                    //case "computer":
                    //    return ResponsesComputerTool.DeserializeResponsesComputerTool(element, options);
                    //case "namespace":
                    //    return ResponsesNamespaceToolParam.DeserializeResponsesNamespaceToolParam(element, options);
                    //case "tool_search":
                    //    return ResponsesToolSearchToolParam.DeserializeResponsesToolSearchToolParam(element, options);
                }
            }
            return UnknownAzureResponsesTool.DeserializeUnknownAzureResponsesTool(element, options);
        }
    }
}